<div class="bottom-navigation">
	<ul>
		<li><a href="#" selected><i class="md-icon">face</i><span>Face</span></a></li>
		<li><a href="#"><i class="md-icon">face</i><span>Face</span></a></li>
		<li><a href="#"><i class="md-icon">face</i><span>Face</span></a></li>
		<li><a href="#"><i class="md-icon">face</i><span>Face</span></a></li>
		<li><a href="#"><i class="md-icon">face</i><span>Face</span></a></li>
	</ul>
</div>