<?php
use Oslo\Core\Config;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=Config::website()["PAGE_TITLE"]?></title>
	<script type="text/javascript" src="<?=ABSOLUTE_ROOT?>includes/scripts/jquery.min.js"></script>
	<script type="text/javascript" src="<?=ABSOLUTE_ROOT?>includes/scripts/clipboard.min.js"></script>
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="<?=ABSOLUTE_ROOT?>includes/styles/global.css" rel="stylesheet">
    <link href="<?=ABSOLUTE_ROOT?>includes/styles/components.css" rel="stylesheet">
    <script src="<?=ABSOLUTE_ROOT?>includes/scripts/smooth_scroll.js"></script>
    <script src="<?=ABSOLUTE_ROOT?>includes/scripts/autosize.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <meta property="og:type" content="website" />
    <meta property="og:title" content="<?=Config::website()["SITE_NAME"]?>" />
    <meta property="og:url" content="<?=Config::website()["SITE_URL"]?>" />
    <meta property="og:site_name" content="<?=Config::website()["SITE_NAME"]?>" />
    <meta property="og:image" content="<?=Config::website()["SITE_IMG"]?>" />
    <meta name="twitter:site" content="<?=Config::website()["SITE_TWITTER"]?>" />
    <link rel="shortcut icon" href="<?=ABSOLUTE_ROOT?>favicon.ico">
    <meta name="theme-color" content="<?=Config::website()["PRIMARY_COLOR"]?>">
    <?php
    loadJavascript("includes/scripts/app/components/");
    loadJavascript("includes/scripts/app/extensions/");
    loadJavascript("includes/scripts/app/objects/");
    loadJavascript("includes/scripts/app/");
    ?>
</head>
<body name="tp">
<?php
foreach($this->_cdir as $name => $component)
    require_once($component);
?>
<div class="view scroll">
    <?=$__RENDER__["BODY"]?>
</div>
<?=$__RENDER__["BOTTOM_NAVIGATION"]?>
<div class="data action-bar ripple ripple-black">
    <div class="table">
        <div class="row">
            <div class="cell middle">
                <span class="data-label"></span>
            </div>
            <div class="cell fit">
                <ul class="nav">
                    <li><a><span><i class="md-icon">select_all</i></span></a></li>
                    <li><a><span><i class="md-icon">more_vert</i></span></a>
                        <ul class="menu">
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="bottom-sheet scroll"></div>
<div class="dialog-box scroll"></div>
<div class="black-trans"></div>
<div class="snackbar row"></div>
<div class="loading">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="6" stroke-miterlimit="10"/>
    </svg>
</div>
<script>
	new Clipboard("a[data-clipboard-text]");
</script>
</body>
</html>