<div class="action-bar ripple ripple-black">
    <div class="table">
        <div class="row">
            <div class="cell middle">
                <a class="menu-icon"><i class="md-icon white-text">menu</i></a>
                <span class="title">Oslo Framework</span>
            </div>
            <div class="cell fit">
                <ul class="nav">
                    <script>
                        var c = new Content();
                        c.url = Config.ROOT+"/o_db/";
                    </script>
                    <li><a onclick="DialogBox.showContent(c)"><span><i class="md-icon">face</i>Fork me on Github</span></a></li>
                        <!--<ul  class="menu">-->
                        <!--    <script>-->
                        <!--        var c = new Content();-->
                        <!--        c.direct();-->
                        <!--        c.url = "o_bs/test";-->
                        <!--    </script>-->
                        <!--    <li><a onclick="BottomSheet.showContent(c)"><i class="md-icon">face</i>Hehe</a></li>-->
                        <!--    <li><a onclick="Loading.show()">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, ullam.</a></li>-->
                        <!--    <li><a onclick="Loading.hide()">Hehe</a></li>-->
                        <!--    <li><a href="#">Hehe</a></li>-->
                        <!--</ul>-->

                </ul>
            </div>
        </div>
    </div>
</div>