<h3>Title</h3>
<div class="content wrap scroll">
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam aliquid amet atque deleniti dolorem doloribus error, eum exercitationem hic illum iste iusto labore laborum maxime nobis numquam officiis optio quaerat quam quod repellendus sed sint sit sunt, suscipit tempora voluptatem voluptatibus? Accusamus adipisci cumque distinctio, eaque et fugit libero non quia ullam? Accusantium eaque illum laborum nihil odit quisquam sit velit voluptas voluptate voluptatum? Animi exercitationem in iste molestiae, odio pariatur sed vel vitae. Aliquam dicta error ex expedita libero nobis perspiciatis praesentium reprehenderit. A accusamus ad architecto corporis doloribus dolorum est eum, explicabo, minima molestiae nam odio quod suscipit?
</div>
<div class="action">
	<ul class="buttons right">
		<li><a onclick="Slider.disable();" class="flat_button">Close</a></li>
		<li><a onclick="DialogBox.loader()" class="flat_button">Fork</a></li>
	</ul>
</div>